#!/usr/bin/env perl

use strict;
use Getopt::Long;

my $print_usage = 0;

my $usage = <<USAGE;

  This script

  Mark Stenglein,  X/Y/2014

  Usage: $0 [-h] 

   [-h]          print this message

USAGE

if ((scalar @ARGV == 0) and -t STDIN) { print $usage and exit; }

GetOptions ("h" => \$print_usage);

my $pwd = `pwd`;
chomp $pwd;
print "cd $pwd\n";

# open the pdb
print "open 6vxx.pdb\n";

# unshow side chains
print "~show\n";

# rotate it so it's pointed up
print "turn y 90\n";
print "turn z 90\n";

# use a publication preset (silhouette, licorice)
print "preset apply pub 2\n";

# color everything light steel blue
print "color lightsteelblue :*.A-C\n";

while (<>)
{
   chomp;
 
   # ignore comment lines
   if (/^\s*#/) { next; }
   # ignore blank lines
   if (/^\s*$/) { next; }
   
   # csv format
   my @fields = split ",";

   my $range = $fields[0];
   my $color = $fields[1];
   my $label = $fields[2];
   my $representation = $fields[3];

   # color them
   print "color $color :$range.A-C\n";

   if ($representation eq "none")
   {
      # don't do anything
   }
   else
   {
      # show the atoms
      print "display :$range.A-C\n";

      # represent atoms as spheres 
      print "represent $representation :$range.A-C\n";
   }

   # label the residue
   # print "rlabel :$range.A-C\n";
}


# zoom out a bit
print "scale 0.75\n";
